Repository jupyter/nbclassic, pull requests merged in 2021-05, with the labels that each got.

#52 Support creating terminal with a given name.
  nbclassic/terminal/handlers.py
Labels: enhancement

#55 BUG fix: correct redirection to {base_url}/edit/*.
  nbclassic/notebookapp.py
Labels: bug

#56 patch server's sorted_extensions to prioritize nbclassic
  nbclassic/nbserver.py
Labels: maintenance

#57 Add changelog entry for 0.3 release
  CHANGELOG.md
Labels: documentation

#58 bump jupyter_server dependency to 1.8
  setup.py
Labels: maintenance

#59 Add changelog for 0.3.1 release
  CHANGELOG.md
Labels: documentation
