Repository jupyter/nbclassic, pull requests merged in 2022-07, with the labels that each got.

#117 Automated Changelog Entry for 0.4.0 on main
  CHANGELOG.md
Labels: documentation

#122 Relax assert for IPythonHandler in case of notebook<6
  nbclassic/__init__.py
Labels: bug

#123 Don't shim notebook if notebook<7 is available
  nbclassic/__init__.py
  nbclassic/shim_notebook.py
Labels: enhancement

#125 Update release notes for 0.4.2
  CHANGELOG.md
Labels: maintenance

#126 Handle execution errors with empty traceback entries similar to Lab
  nbclassic/static/notebook/js/outputarea.js
Labels: enhancement

#127 fix enable-on-install
  setup.cfg
  setup.py
Labels: bug

#131 Fix handling of dev version when releasing
  .github/workflows/check-release.yml
  RELEASE.md
Labels: maintenance

#130 fix some import errors in 0.4
  nbclassic/bundler/handlers.py
  nbclassic/bundler/tools.py
  nbclassic/notebookapp.py
Labels: bug

#132 Automated Changelog Entry for 0.4.3 on main
  CHANGELOG.md
Labels: documentation
