Repository jupyter/nbclassic, pull requests merged in 2022-11, with the labels that each got.

#171 Updating contributing docs for playwright tests
  CONTRIBUTING.rst
Labels: documentation

#172 Handle async and sync contents managers
  nbclassic/edit/handlers.py
  nbclassic/tree/handlers.py
  tests/test_notebookapp.py
Labels: bug

#174 Documentation for the extensions configurator
  docs/source/nbclassic_dev_faq.rst
  nbclassic/static/base/js/namespace.js
Labels: documentation

#175 Add dependabot config
  .github/dependabot.yml
Labels: maintenance

#181 Align setup.py and setup.cfg
  nbclassic/static/base/js/namespace.js
  pyproject.toml
  setup.cfg
  setup.py
Labels: bug

#186 Upgrade moment javascript package
  bower.json
Labels: maintenance
