Repository jupyter/nbclassic, pull requests merged in 2022-09, with the labels that each got.

#148 Fix resource display when redirecting from /notebooks/*
  nbclassic/notebookapp.py
Labels: bug

#134 Updating documentation for nbclassic
  CONTRIBUTING.rst
  docs/source/conf.py
  docs/source/config_overview.rst
  docs/source/development_faq.rst
  docs/source/frontend_config.rst
  docs/source/index.rst
  docs/source/nbclassic.rst
  docs/source/nbclassic_dev_faq.rst
  docs/source/notebook.rst
  docs/source/public_server.rst
  docs/source/security.rst
  docs/source/troubleshooting.rst
  docs/source/ui_components.rst
Labels: documentation

#152 Updating JS Dependencies
  bower.json
  nbclassic/templates/page.html
  setupbase.py
  tools/build-main.js
Labels: maintenance

#153 Stop looking in the old IPython directory for nbextensions
  nbclassic/notebookapp.py
Labels: enhancement
