Repository jupyter/nbclassic, pull requests merged in 2022-10, with the labels that each got.

#156 fix: display the correct about box if jupyter notebook command is used
  nbclassic/static/base/js/namespace.js
  nbclassic/static/notebook/js/about.js
Labels: bug

#158 Automated Changelog Entry for 0.4.5 on main
  CHANGELOG.md
Labels: documentation

#159 Use `var` instead of `const` to ensure js-test succeed
  nbclassic/static/notebook/js/about.js
Labels: bug

#155 Adds new file custom-preload that is loaded in a different order than custom.js before the main.js script is executed
  nbclassic/static/custom/custom-preload.js
  nbclassic/static/edit/js/main.js
  nbclassic/static/notebook/js/main.js
  nbclassic/static/terminal/js/main.js
  nbclassic/static/tree/js/main.js
  nbclassic/templates/page.html
  tools/build-main.js
Labels: feature

#160 add badge for documentation
  README.md
Labels: documentation

#161 Automated Changelog Entry for 0.4.6 on main
  CHANGELOG.md
Labels: documentation

#165 Allow NBClassic to work with NB7 and ServerApp.base_url
  nbclassic/__init__.py
  nbclassic/bundler/handlers.py
  nbclassic/edit/handlers.py
  nbclassic/notebook/handlers.py
  nbclassic/notebookapp.py
  nbclassic/static/edit/js/menubar.js
  nbclassic/static/notebook/js/about.js
  nbclassic/static/notebook/js/kernelselector.js
  nbclassic/static/notebook/js/main.js
  nbclassic/static/notebook/js/menubar.js
  nbclassic/static/notebook/js/notebook.js
  nbclassic/static/services/config.js
  nbclassic/static/services/contents.js
  nbclassic/static/services/sessions/session.js
  nbclassic/static/terminal/js/main.js
  nbclassic/static/tree/js/main.js
  nbclassic/static/tree/js/newnotebook.js
  nbclassic/static/tree/js/notebooklist.js
  nbclassic/static/tree/js/sessionlist.js
  nbclassic/static/tree/js/terminallist.js
  nbclassic/templates/page.html
  nbclassic/tree/handlers.py
Labels: bug

#166 Add a redirect from /nbclassic to /nbclassic/tree if both notebook>=7 if both notebook>=7 and nbclassic are installed
  nbclassic/notebookapp.py
  nbclassic/static/base/js/namespace.js
Labels: enhancement

#168 Fix/nbclassic base url
  nbclassic/notebookapp.py
  nbclassic/templates/page.html
Labels: feature

#169 Automated Changelog Entry for 0.4.7 on main
  CHANGELOG.md
Labels: documentation
