Repository jupyter/nbclassic, pull requests merged in 2023-02, with the labels that each got.

#216 CI Test Fixes Round 3
  nbclassic/tests/end_to_end/test_save_as_notebook.py
  nbclassic/tests/end_to_end/test_save_readonly_as.py
  nbclassic/tests/end_to_end/utils.py
Labels: bug, maintenance

#215 Add news banner and log
  docs/source/nbclassic.rst
  nbclassic/notebookapp.py
  nbclassic/static/base/js/namespace.js
  nbclassic/templates/page.html
Labels: enhancement

#219 Automated Changelog Entry for 0.5.2 on main
  CHANGELOG.md
Labels: documentation

#220 Fix banner icons
  nbclassic/static/base/js/namespace.js
  nbclassic/templates/page.html
Labels: bug

#221 Fix generating of .mo and .json files for nl translation
  setupbase.py
Labels: bug

#226 CI Test Fixes Round 4
  nbclassic/tests/end_to_end/conftest.py
  nbclassic/tests/end_to_end/test_dashboard_nav.py
  nbclassic/tests/end_to_end/utils.py
Labels: maintenance
