Repository jupyter/nbclassic, pull requests merged in 2023-03, with the labels that each got.

#230 Automated Changelog Entry for 0.5.3 on main
  CHANGELOG.md
Labels: documentation

#232 CI Test Fixes Round 5
  nbclassic/tests/end_to_end/test_dualmode_arrows.py
  nbclassic/tests/end_to_end/utils.py
Labels: bug, maintenance

#234 CI Test Fixed Round6a
  .github/workflows/playwright.yml
  nbclassic/tests/end_to_end/test_dashboard_nav.py
Labels: bug, maintenance

#236 Copy marked.umd.js to marked.js and revert loading
  nbclassic/static/base/js/markdown.js
  nbclassic/static/base/js/namespace.js
  nbclassic/static/notebook/js/shortcuteditor.js
  nbclassic/static/tree/js/notebooklist.js
  setupbase.py
Labels: bug

#239 Automated Changelog Entry for 0.5.4 on main
  CHANGELOG.md
Labels: documentation
