Repository jupyter/nbclassic, pull requests merged in 2023-01, with the labels that each got.

#196 Update documentation
  docs/source/nbclassic.rst
  docs/source/nbclassic_dev_faq.rst
Labels: documentation

#194 Update the project URL
  setup.cfg
Labels: documentation

#192 fix loading of static and template path config
  nbclassic/notebookapp.py
Labels: bug

#197 Remove duplicate notebook_shim from setup.cfg
  setup.cfg
Labels: maintenance, dependencies

#201 Upgrade to marked 4.0.10
  bower.json
  nbclassic/static/base/js/markdown.js
  nbclassic/static/notebook/js/shortcuteditor.js
  nbclassic/static/tree/js/notebooklist.js
  setupbase.py
Labels: enhancement, dependencies

#202 Ci test fixes round1
  nbclassic/tests/end_to_end/test_save.py
Labels: bug, maintenance

#203 Automated Changelog Entry for 0.5.0 on main
  CHANGELOG.md
Labels: documentation

#205 Add static and templates as artifact for hatch build
  pyproject.toml
Labels: bug

#207 Automated Changelog Entry for 0.5.1 on main
  CHANGELOG.md
Labels: documentation

#210 Update get_rendered_contents further marked javascript upgrade
  nbclassic/tests/end_to_end/test_markdown.py
Labels: bug

#212 CI Test Fixes Round 2
  nbclassic/tests/end_to_end/test_save_readonly_as.py
  nbclassic/tests/end_to_end/utils.py
Labels: bug, maintenance
