Repository jupyter/nbclassic, pull requests merged in 2025-04, with the labels that each got.

#329 Update JavaScript dependencies
  .github/workflows/js.yml
  .github/workflows/playwright.yml
  CONTRIBUTING.rst
  package.json
  yarn.lock
Labels: maintenance

#330 Fix set-output deprecation warnings
  .github/workflows/check-release.yml
  .github/workflows/docs.yml
Labels: maintenance

#332 Upload release artifacts on push
  .github/workflows/check-release.yml
Labels: maintenance

#331 Add Release workflows
  .github/workflows/playwright.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-changelog.yml
  .github/workflows/publish-release.yml
Labels: maintenance

#337 Support offline source distribution builds
  .github/workflows/check-release.yml
  .github/workflows/docs.yml
  .github/workflows/js.yml
  .github/workflows/pythonpackage.yml
  CONTRIBUTING.rst
  pyproject.toml
  tools/install_pydeps.py
Labels: bug

#340 Fix Hatch build fails in src directory
  .gitignore
Labels: bug

#341 Update releaser docs
  RELEASE.md
Labels: documentation
